events.listen('block.registry', function (e) {
  e.create('platinum_block').material('iron').hardness(0.5).displayName('Block of Platinum')
  e.create('tungsten_block').material('iron').hardness(0.5).displayName('Block of Tungsten')
  e.create('quarkonium_block').material('iron').hardness(0.5).displayName('Block of Quarkonium')
  e.create('obsidian_ingot_block').material('iron').hardness(0.5).displayName('Obsidian Ingot Block')
  e.create('alfsteel_crux').material('rock').hardness(0.5).displayName('Alfsteel Crux')
  e.create('smithing_machine_block').material('iron').hardness(0.5).displayName('Smithing Machine Block')
  e.create('aquamarine_block').material('iron').hardness(0.5).displayName('Aquamarine Block')
  e.create('machinarium_block').material('iron').hardness(0.5).displayName('Machinarium Block')
  e.create('waxed_fiery_block').material('iron').hardness(0.5).displayName('Waxed Block of Fiery Metal')
  e.create('ultimate_comb_block').material('coral').hardness(0.5).displayName('Ultimate Honeycomb Block')
  e.create('chaotic_crux').material('rock').hardness(0.5).displayName('Chaotic Crux')
  e.create('chaotic_bee_flower').material('rock').hardness(0.5).displayName('Chaotic Bee Flower')
  e.create('dragon_bee_flower').material('rock').hardness(0.5).displayName('Dragon Bee Flower')
  e.create('mlsexy').material('rock').hardness(0.5).displayName('Sexy')
  e.create('tungsten_nether_ore').material('rock').hardness(0.5).displayName('Nether Tungsten Ore')
  e.create('tungsten_ore').material('rock').hardness(0.5).displayName('Tungsten Ore')
  e.create('ultimate_crux').material('rock').hardness(0.5).displayName('Ultimate Crux')
})