events.listen('block.registry', function (e) {
  e.create('resourcefulbees_trophy').material('rock').hardness(1).displayName('Resourcefulbees Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('mysticalagriculture_trophy').material('rock').hardness(1).displayName('Mysticalagriculture Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('jellyfishing_trophy').material('rock').hardness(1).displayName('Jellyfishing Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('woot_trophy').material('rock').hardness(1).displayName('Woot Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('refined_trophy').material('rock').hardness(1).displayName('Refined Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('mahoutsukai_trophy').material('rock').hardness(1).displayName('Mahou Tsukai Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('astralsorcery_trophy').material('rock').hardness(1).displayName('Astral Sorcery Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('rats_trophy').material('rock').hardness(1).displayName('Rats Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('twilightforest_trophy').material('rock').hardness(1).displayName('Twilight Forest Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('sonicraft_trophy').material('rock').hardness(1).displayName('Sonicraft Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('create_trophy').material('rock').hardness(1).displayName('Create Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('immersiveengineering_trophy').material('rock').hardness(1).displayName('Immersive Engineering Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('industrialforegoing_trophy').material('rock').hardness(1).displayName('Industrial Foregoing Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('mekanism_trophy').material('rock').hardness(1).displayName('Mekanism Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('thermal_trophy').material('rock').hardness(1).displayName('Thermal Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('psi_trophy').material('rock').hardness(1).displayName('PSI Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('extendedcrafting_trophy').material('rock').hardness(1).displayName('Extended Crafting Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('gobber2_trophy').material('rock').hardness(1).displayName('Gobber Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('miscellaneous_trophy').material('rock').hardness(1).displayName('Miscellaneous Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('draconicevolution_trophy').material('rock').hardness(1).displayName('Draconic Evolution Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('forbidden_arcanus_trophy').material('rock').hardness(1).displayName('Forbidden Arcanus Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('botania_trophy').material('rock').hardness(1).displayName('Botania Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('eidolon_trophy').material('rock').hardness(1).displayName('Eidolon Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('bloodmagic_trophy').material('rock').hardness(1).displayName('Blood Magic Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('pneumaticcraft_trophy').material('rock').hardness(1).displayName('Pneumatic Craft Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('powergen_trophy').material('rock').hardness(1).displayName('PowerGen Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('envirotech_trophy').material('rock').hardness(1).displayName('Environmental Tech Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('rftools_trophy').material('rock').hardness(1).displayName('RFTools Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('powah_trophy').material('rock').hardness(1).displayName('Powah Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  e.create('projecte_trophy').material('rock').hardness(1).displayName('ProjectE Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
})