onEvent('item.tooltip', tooltip => {

    //§a = Common / §6 Uncommon / §b Rare / §d Very Rare

    tooltip.add('janoeo:zinc_ore', ['§aY:5-64'])
    tooltip.add('thermal:copper_ore', ['§aY:40-64'])
    tooltip.add('thermal:tin_ore', ['§aY:20-55'])
    tooltip.add('thermal:lead_ore', ['§6Y:10-40'])
    tooltip.add('thermal:nickel_ore', ['§bY:30-60'])
    tooltip.add('janoeo:uranium_ore', ['§aY:5-30'])
    tooltip.add('janoeo:aluminium_ore', ['§aY:10-60'])
    tooltip.add('thermal:silver_ore', ['§6Y:20-30'])
    tooltip.add('iceandfire:amythest_ore', ['§6Y:25-45'])
    tooltip.add('thermal:sapphire_ore', ['§6Y:25-45'])
    tooltip.add('thermal:ruby_ore', ['§6Y:25-45'])
    tooltip.add('mekanism:osmium_ore', ['§aY:25-60'])
    tooltip.add('ars_nouveau:arcane_ore', ['§aY:25-50'])
    tooltip.add('kubejs:tungsten_ore', ['§dY:5-16'])
    tooltip.add('forbidden_arcanus:dark_runestone', ['§dY:5-8'])
    tooltip.add('minecraft:iron_ore', ['§aY:15-60'])
    tooltip.add('minecraft:redstone_ore', ['§aY:5-16'])
    tooltip.add('minecraft:diamond_ore', ['§bY:5-16'])
    tooltip.add('minecraft:gold_ore', ['§6Y:5-25'])
    tooltip.add('minecraft:lapis_ore', ['§6Y:5-20'])
    tooltip.add('forbidden_arcanus:arcane_crystal_ore', ['§6Y:5-20'])
    tooltip.add('minecraft:coal_ore', ['§aY:5-64'])
    tooltip.add('bigreactors:yellorite_ore', ['§6Y:5-32'])
    tooltip.add('draconicevolution:overworld_draconium_ore', ['§dY:5-10'])
    tooltip.add('astralsorcery:rock_crystal_ore', ['§dY:5-8'])
    tooltip.add('forbidden_arcanus:runestone', ['§dY:5-15'])
    tooltip.add('#resourcefulbees:valid_apiary', ['§7§oValid Apiary Block'])
    tooltip.add(['amb:driftwood_lectern', 'amb:warped_lectern', 'amb:crimson_lectern', 'amb:dark_oak_lectern', 'amb:acacia_lectern', 'amb:jungle_lectern', 'amb:birch_lectern', 'amb:spruce_lectern', 'minecraft:loom', 'iceandfire:lectern', 'morevillagers:hunting_post', 'minecraft:smoker', 'minecraft:stonecutter', 'resourcefulbees:t1_apiary', 'morevillagers:woodworking_table', 'immersiveengineering:workbench', 'minecraft:grindstone', 'jellyfishing:grill', 'morevillagers:gardening_table', 'minecraft:fletching_table', 'morevillagers:decayed_workbench', 'immersiveengineering:craftingtable', 'minecraft:composter', 'pneumaticcraft:charging_station', 'minecraft:cauldron', 'minecraft:cartography_table', 'minecraft:brewing_stand', 'morevillagers:blueprint_table', 'minecraft:blast_furnace', 'minecraft:barrel', 'minecraft:anvil', 'buzzier_bees:honey_pot', 'minecraft:smithing_table', 'morevillagers:purpur_altar', 'morevillagers:oceanography_table', 'immersiveengineering:current_transformer'], ['§7§oVillager Workstation'])
    tooltip.add(['kubejs:emc1', 'kubejs:emc2', 'kubejs:emc3', 'kubejs:emc4', 'kubejs:emc5'], ['§4Only used for EMC'])

  })